[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
[build]
  base = "."
  publish = "public/"
  command = "npm run prod"
